lancerJeu()
let inputEcriture = document.getElementById("inputEcriture")
let btnValidationMot = document.getElementById("btnValiderMot")
let zoneProposition = document.querySelector(".zoneProposition")
let zoneScore = document.querySelector('.zoneScore span')
let optionSource = document.querySelectorAll("input")